### ISSUE TITLE
Alteri buttons shown on :hover not accessible on touch device

### ISSUE THREAD

**Issue by alex-rind** [fhstp/easynwk-web#40]

**Comment by alex-rind** [comment]
On Android the buttons appear after touching the panel entry (which also has selection as side effect).
The buttons are clickable even when they are not visible.

**Comment by alex-rind** [comment]
use a media query to always show buttons on touch devices 👍 

```css
@media(hover: hover) and (pointer: fine) {
    nav a:hover {
        background: yellow;
    }
}
```

cp. https://medium.com/@mezoistvan/finally-a-css-only-solution-to-hover-on-touchscreens-c498af39c31c
